/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "eqebcfwheuxbnpimzqot"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZWJjZndoZXV4Ym5waW16cW90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NDUzMDQsImV4cCI6MjA3NzAyMTMwNH0.IZRORk1DuOumC2gH2fzVXjgHxPhAIJZi-B8y-tVJxWY"